---
title: "Tidy tuesday bike frequencies seattle"
author: "Luca"
date: "06/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(lubridate)
library(scales)
theme_set(theme_light())

bike_traffic_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-02/bike_traffic.csv")


bike_traffic <- bike_traffic_raw %>%
  mutate(date = mdy_hms(date))


bike_traffic %>% 
  ggplot(aes(date, fill = is.na(bike_count))) +
  geom_histogram() +
  facet_grid(crossing ~ direction)
```


# When in the day do we see bikers/pedestrians?

```{r}
bike_traffic %>% 
  group_by(hour = hour(date)) %>% 
  summarise_at(vars(bike_count, ped_count), sum, na.rm = TRUE) %>% 
  pivot_longer(cols = c("ped_count", "bike_count"), names_to = "type", values_to = "count") %>% 
  ggplot(aes(hour, count, color = type)) +
  geom_line() +
  geom_point()

bike_traffic %>% 
  group_by(crossing,
           hour = hour(date)) %>% 
  summarise_at(vars(bike_count, ped_count), sum, na.rm = TRUE) %>% 
  ggplot(aes(hour, bike_count, color = crossing)) +
  geom_line() +
  geom_point()


bike_traffic %>% 
  group_by(crossing,
           hour = hour(date)) %>% 
  summarize_at(vars(bike_count, ped_count), sum, na.rm = TRUE) %>% 
  mutate(pct_bike = bike_count / sum(bike_count)) %>% 
  ggplot(aes(hour, pct_bike, color = crossing)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = percent_format()) +
  labs(title = "When in the day do people bike trough these Seattle crossings?",
       subtitle = "Based on crossings from 2013 - 2019",
       y = "",
       x = "Count",
       color = "Crossing")
```


```{r}
bike_traffic %>% 
  mutate(hour = hour(date)) %>% 
  mutate(time_window = case_when(
    between(hour, 7, 10) ~ "Morning Commute",
    between(hour, 11, 15) ~ "Midday",
    between(hour, 16, 18) ~ "Evening Commute",
    TRUE ~ "Night"
  )) %>% 
  group_by(crossing, 
           time_window) %>% 
  summarize(pct_missing = mean(is.na(bike_count) * 100),
            bike_count = sum(bike_count, na.rm = TRUE))
  
bike_by_timewindow <- bike_traffic %>% 
  mutate(hour = hour(date)) %>% 
  mutate(time_window = case_when(
    between(hour, 7, 10) ~ "MorningCommute",
    between(hour, 11, 15) ~ "Midday",
    between(hour, 16, 18) ~ "EveningCommute",
    TRUE ~ "Night"
  )) %>% 
  group_by(crossing, 
           time_window) %>% 
  summarize(number_missing = sum(is.na(bike_count)),
            bike_count = sum(bike_count, na.rm = TRUE)) %>%  
  mutate(pct_bike = bike_count / sum(bike_count))

bike_by_timewindow %>% 
  select(-number_missing, -bike_count) %>% 
  spread(time_window, pct_bike) %>% 
  mutate(TotalCommute = EveningCommute + MorningCommute) %>% 
  arrange(desc(TotalCommute))
  
bike_by_timewindow %>% 
  ggplot(aes(time_window, pct_bike)) +
  geom_col() +
  coord_flip() +
  facet_wrap(~ crossing)


bike_by_timewindow %>% 
  group_by(crossing) %>% 
  summarize(total_bikes = sum(bike_count),
            pct_commute = sum(bike_count[str_detect(time_window, "Commute")]) / total_bikes) %>% 
  ggplot(aes(total_bikes, pct_commute)) + 
  geom_point() +
  scale_x_log10()
```


```{r}
bike_traffic %>% 
  group_by(crossing,
           weekday = wday(date, label = TRUE),
           hour = hour(date)) %>% 
  summarise(total_bikes = sum(bike_count, na.rm = TRUE)) %>% 
  group_by(crossing) %>% 
  mutate(pct_bike = total_bikes / sum(total_bikes, na.rm = TRUE)) %>% 
  ggplot(aes(hour, pct_bike, color = crossing)) +
  geom_line(show.legend = FALSE) +
  scale_y_continuous(labels = percent_format()) +
  facet_wrap(crossing ~ weekday) +
  labs(title = "When in the week do people bike?",
       subtitle = "Based on Seattle crossings from 2013 - 2019",
       x = "Time of week",
       y = "")
  
```

```{r}
bike_traffic %>% 
  filter(date > "2014-01-01" & date < "2017-01-01") %>% 
  filter(bike_count <= 2000) %>% 
  group_by(crossing,
           month = month(date, label = TRUE)) %>% 
  summarise(total_bikes = sum(bike_count)) %>% 
  mutate(pct_bikes = total_bikes / sum(total_bikes)) %>% 
  ggplot(aes(month, pct_bikes, color = crossing, group = crossing)) +
  geom_line() +
  scale_y_continuous(labels = percent_format()) +
  labs(title = "When in the week do people bike?",
       subtitle = "Based on Seattle crossings from 2014 - 2016",
       x = "",
       y = "% of bikes") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


### What directions do people commute by bike?

```{r}
bike_by_direction_hour_crossing <- bike_traffic %>%
  filter(crossing != "MTS Trail",
         !wday(date, label = TRUE) %in% c("Sat", "Sun"),
         direction %in% c("North", "South")) %>%
  mutate(hour = hour(date)) %>%
  group_by(crossing,
           direction,
           hour) %>%
  summarize(bike_count = sum(bike_count, na.rm = TRUE)) %>%
  mutate(pct_bike = bike_count / sum(bike_count))


bike_by_direction_hour_crossing %>%
  group_by(crossing) %>%
  mutate(average_hour = sum((hour * pct_bike)[direction == "North"])) %>%
  ungroup() %>%
  mutate(crossing = fct_reorder(crossing, average_hour)) %>%
  ggplot(aes(hour, pct_bike, color = direction)) +
  geom_line() +
  facet_grid(crossing ~ .) +
  scale_y_continuous(labels = percent_format()) +
  labs(x = "Time of day",
       y = "% of bike crossings happening in this hour",
       title = "In which directions do people commute by bike?",
       subtitle = "Based on weekday crossings at six Seattle locations from 2014-February 2019",
       color = "Direction")
```









