---
title: "World Freedom Index"
author: "Luca"
date: "28/02/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(glue)
library(countrycode)

theme_set(theme_light())
```


Download the data

```{r}
freedom <- tt_load("2022-02-22")$freedom %>% 
  janitor::clean_names() %>% 
  rename(civil_liberties = cl,
         political_rights = pr) %>% 
  # fix with the countrycode-package!
  mutate(country_code = countrycode(country, "country.name", "iso2c"))

freedom

freedom %>% 
  count(year) %>% 
  arrange(year)
```

from 1995 to 2020
about 193 countries (some missing data in earlier years)


Civil liberty

```{r}
freedom %>% 
  ggplot(aes(civil_liberties)) +
  geom_histogram()


freedom %>% 
  filter(year == 2020) %>% 
  arrange(desc(civil_liberties))

# scales from 1 to 7 (1 = best, 7 = worst)

```


Look just at 2020

Correlation between region and freedom indices

```{r}
by_region <- freedom %>% 
  filter(year == 2020) %>% 
  group_by(region_name) %>% 
  summarise(n_countries = n(),
            avg_civil_liberties = mean(civil_liberties),
            avg_political_rights = mean(political_rights),
            pct_free = mean(status == "F")) 

by_region %>% 
  ggplot(aes(avg_civil_liberties, avg_political_rights)) + 
  geom_point(aes(size = n_countries),
             alpha = 0.25) +
  geom_abline(color = "red") + 
  geom_text(aes(label = glue("{region_name}: {round(pct_free, 1)}% countries are free")),
            color = "black",
            vjust = 0,
            hjust = 1.05) +
  expand_limits(x = 0,
                y = 0,
                size = 0) +
  scale_x_continuous(breaks = seq(0, 5, 1)) +
  scale_y_continuous(breaks = seq(0, 5, 1)) + 
  labs(title = "Freedom Indices by Region",
       x = "Civil Liberties",
       y = "Political Rights",
       size = "Number of Countries")
```


Correlation between countries and freedom indices

```{r}
# is the mean the right value?
freedom %>% 
  filter(year == 2020) %>% 
  ggplot(aes(civil_liberties, political_rights)) +
  geom_jitter(width = 0.2, 
              height = 0.2) +
  geom_abline(color = "red") + 
  scale_x_continuous(breaks = seq(0, 7, 1)) + 
  scale_y_continuous(breaks = seq(0, 7, 1)) + 
  expand_limits(x = 0, 
                y = 0) + 
  labs(title = "Freedom Indices by Country",
       x = "Civil Liberties",
       y = "Political Rights")

# look at the distribution as well!
freedom %>% 
  filter(year == 2020) %>% 
  pivot_longer(cols = c(civil_liberties, political_rights), 
               names_to = "metric",
               values_to = "value") %>% 
  mutate(metric = str_to_title(str_replace_all(metric, "_", " ")),
         region_name = fct_reorder(region_name, value)) %>% 
  count(region_name, metric, value) %>% 
  ggplot(aes(value, n)) + 
  geom_col() +
  scale_x_continuous(breaks = seq(1, 7, 1))  +
  facet_grid(region_name ~ metric) +
  labs(title = "Distribution of Freedom Index Rating per Region",
       x = "Freedom Index Rating",
       y = "Number of Countries")
  
```


Over time

```{r}
freedom_long <- freedom %>% 
  pivot_longer(cols = c(civil_liberties, political_rights),
               names_to  = "metric",
               values_to = "value") %>% 
  mutate(metric = str_to_title(str_replace_all(metric, "_", " ")),
         region_name = fct_reorder(region_name, value))


# create second data set for the overall trend!
overall <- freedom_long %>% 
  group_by(year, metric) %>% 
  summarise(avg_rating = mean(value))

freedom_long %>% 
  group_by(year, region_name, metric) %>% 
  summarise(avg_rating = mean(value)) %>% 
  ggplot(aes(year, avg_rating)) +
  geom_line(aes(color = region_name)) +
  geom_line(data = overall,
            aes(year, avg_rating),
            size = 2) + 
  facet_wrap(~ metric) + 
  
  # more intuive to understand!
  scale_y_reverse(breaks = seq(1, 5, 1)) +
  expand_limits(y = 1) + 
  
  # change order of the legend!
  #scale_color_discrete(guide = guide_legend(reverse = TRUE)) +
  
  labs(title = "Word Freedom Index Rating over Time",
       subtitle = "Overall trend is represented in black",
       x = "Year",
       y = "Word Freedom Index Rating",
       color = "Region")

# other trick video (24:00)
#freedom_long %>% 
#  mutate(region_name = "Overall") %>% 
#  bind_rows(freedom_long) %>% 

```





World bank data

```{r}
library(WDI)
gdp_percap <- WDI(indicator = "NY.GDP.PCAP.CD",
                  extra = TRUE,
                  start = 1995,
                  end = 2020) %>% 
  as_tibble()
```

Merge with the freedom data
```{r}
freedome_joined <- freedom %>% 
  inner_join(gdp_percap,
             by = c(country_code = "iso2c", "year"),
             suffix = c("", "_wdi"))

# 34:19
```



