---
title: "Life Expectancy"
date: 2024-01-14
output: html_document
editor_options: 
  chunk_output_type: console
---

# TidyTuesday

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(tidytuesdayR)

`%ni%` <- negate(`%in%`)
theme_set(theme_minimal())
```

# Load the weekly Data

Download the weekly data and make available in the `tt` object.

```{r Load}
tt <- tt_load("2023-12-05")
```

\
\

# Life Expectancy
```{r}
life_expectancy <- tt$life_expectancy %>% 
  janitor::clean_names() %>%
  rename("country" = "entity")

life_expectancy_female_male <- tt$life_expectancy_female_male %>% 
  janitor::clean_names() %>% 
  rename("country" = "entity")
```

\
\

## Countries Over Time
```{r}
set.seed(1234)
random_countries <- life_expectancy %>% 
  filter(!str_detect(country, "income|world")) %>%
pull(country) %>% 
  unique() %>% 
  sample(15)

# 1. graph
life_expectancy %>% 
  filter(country %in% random_countries,
         year >= 1800) %>% 
  mutate(country = fct_reorder(country, life_expectancy, last)) %>% 
  ggplot(aes(year, life_expectancy)) + 
  geom_line(aes(group = country,
                color = country)) + 
  geom_line(aes(year, life_expectancy),
            color = "black",
            linewidth = 1.5,
            lty = 5,
            data = life_expectancy %>% 
              filter(country == "World",
                     year >= 1800)) +
  annotate(geom = "Label",
           label = "World",
           fill = "black",
           color = "white",
           x = 1900,
           y = 30) +
  labs(title = "\nLife Expectancy over Time",
       subtitle = "World vs. some random selected Countries",
       x = "\nYear",
       y = "Life Expectancy (in Years)\n",
       color = "") + 
  guides(color = guide_legend(reverse = TRUE))


# 2. graph
life_expectancy %>% 
  filter(str_detect(country, "income"),
         !str_detect(country, "No income")) %>% 
  mutate(country = fct_reorder(country, life_expectancy, last)) %>% 
  ggplot(aes(year, life_expectancy)) + 
  geom_line(aes(group = country,
                color = country)) + 
  geom_line(aes(year, life_expectancy),
            color = "black",
            linewidth = 1.5,
            lty = 5,
            data = life_expectancy %>% 
              filter(country == "World",
                     year >= 1950)) + 
  annotate(geom = "Label",
           label = "World",
           fill = "black",
           color = "white",
           x = 1990,
           y = 65.5) +
  labs(title = "\nLife Expectancy over Time\n",
       x = "\nYear",
       y = "Life Expectancy (in Years)\n",
       color = "") + 
  guides(color = guide_legend(reverse = TRUE))
```

\
\
