---
title: "<br>gfs.bern - Template<br><br>"
output: 
  html_document:
    toc: yes
    code_folding: show
editor_options: 
  chunk_output_type: console
---

\
\


## Setup
```{r message=FALSE, warning=FALSE}
# packages
library(tidyverse)
library(sjlabelled)
library(expss)
library(glue)

# set theme
theme_set(theme_minimal())
```

\
\
\

## Data
```{r message=FALSE, warning=FALSE}
# 1. haven
ess_SPSS_haven <- haven::read_sav(here::here("gfs.bern",
                                             "01_data",
                                             "ESS_subset.sav"))

# 2. expss
ess_SPSS_expss <- expss::read_spss(here::here("gfs.bern",
                                              "01_data",
                                              "ESS_subset.sav")) %>% 
  as_tibble()

# 3. sjlabelled
ess_SPSS_sjlabelled <- sjlabelled::read_spss(here::here("gfs.bern",
                                                        "01_data",
                                                        "ESS_subset.sav")) %>% 
  as_tibble()

# 4. foreign
ess_SPSS_foreign <- foreign::read.spss(here::here("gfs.bern",
                                                  "01_data",
                                                  "ESS_subset.sav"),
                                       use.value.labels = TRUE) %>% 
  as_tibble()
```

\
\

**Variable types depend on the package you choose to read them:**

* haven: dbl + lbl
* expss: labelled
* sjlabelled: factors
* foreign: factors

\
\
\

## 1. Create spss_summary()

\
```{r message=FALSE, warning=FALSE}

spss_summary <- function(data) {
  
  ### 1. create summary-variables
  
  # 1.1. value range
  value_range <- sjlabelled::get_values(data) %>% 
    map(., ~str_c(., collapse = ",\n")) %>% 
    unlist()
  
  # 1.2. value labels
  value_labels <- sjlabelled::get_labels(data) %>% 
    map(., ~str_c(., collapse = ",\n")) %>% 
    unlist()
  
  # 1.3. min value
  min_value <- sjlabelled::as_numeric(data) %>% 
    map_dbl(., ~min(., na.rm = TRUE)) %>% 
    round(0)
  
  # 1.4. median value
  median_value <- sjlabelled::as_numeric(data) %>% 
    map_dbl(., ~median(., na.rm = TRUE)) %>% 
    round(2)
  
  # 1.5. mean value
  mean_value <- sjlabelled::as_numeric(data) %>% 
    map_dbl(., ~mean(., na.rm = TRUE)) %>% 
    round(2)
  
  # 1.6. max value
  max_value <- sjlabelled::as_numeric(data) %>% 
    map_dbl(., ~max(., na.rm = TRUE)) %>% 
    round(0)
  
  # 1.7. variable_class
  variable_class <- map(data, class) %>% 
    map(., ~str_c(., collapse = ",\n")) %>% 
    unlist()
  
  
  ### 2. create tibble
  
  message("Please make check missing values/NAs")
  
  tibble(
    orignial_order = 1:ncol(data),
    variable_name = names(data),
    variable_label = sjlabelled::get_label(data),
    value_range = value_range,
    value_labels = value_labels,
    number_NAs = map_dbl(data, ~sum(is.na(.))),
    percent_NAs = round((number_NAs / nrow(data)) * 100, 2),
    min_value = min_value,
    median_value = median_value,
    mean_value = mean_value,
    max_value = max_value,
    variable_class = variable_class,
    variable_type = map_chr(data, typeof)
  )
  
}

```

\
\

## 2. Test spss_summary()

### 2.1. haven
```{r message=FALSE, warning=FALSE}
# haven
spss_summary(ess_SPSS_haven) %>% 
  knitr::kable(format = "html") %>% 
  kableExtra::kable_styling(bootstrap_options = "bordered", 
                            full_width = FALSE) %>% 
  kableExtra::scroll_box(width = "910px", 
                         height = "600px")
```

\
\

### 2.2. expss
```{r message=FALSE, warning=FALSE}
ess_SPSS_expss %>%
  spss_summary() %>% 
  knitr::kable(format = "html") %>% 
  kableExtra::kable_styling(bootstrap_options = "bordered", 
                            full_width = FALSE) %>% 
  kableExtra::scroll_box(width = "910px", 
                         height = "600px")
```

\
\

### 2.3. sjlabelled
```{r message=FALSE, warning=FALSE}
ess_SPSS_sjlabelled %>% 
  spss_summary() %>% 
  knitr::kable(format = "html") %>% 
  kableExtra::kable_styling(bootstrap_options = "bordered", 
                            full_width = FALSE) %>% 
  kableExtra::scroll_box(width = "910px", 
                         height = "600px")
```

\
\

### 2.4. foreign
```{r message=FALSE, warning=FALSE}
# foreign
spss_summary(ess_SPSS_foreign) %>% 
  knitr::kable(format = "html") %>% 
  kableExtra::kable_styling(bootstrap_options = "bordered", 
                            full_width = FALSE) %>% 
  kableExtra::scroll_box(width = "910px", 
                         height = "600px")
```

\
\