---
title: "2020-05-26_tidy_tuesday_cocktails"
author: "Luca"
date: "24/04/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidytuesdayR)
library(tidyverse)

tt <- tt_load("2020-05-26")

cocktails <- tt$boston_cocktails

cocktails

cocktails %>% 
  count(name)

cocktails %>% 
  count(row_id)

# is row_id == name?
cocktails %>% 
  group_by(name) %>% 
  summarise(ids = n_distinct(row_id)) %>% 
  filter(ids > 1)
# => yes!
```


```{r}
# how many ingredients per cocktail?
cocktails %>% 
  count(name)

# take a look
cocktails %>% 
  filter(name == "1626")

# how many cocktails with n ingredients?
cocktails %>% 
  count(name) %>% 
  count(n)

# cocktails with only 1 ingredient
cocktails %>% 
  group_by(name) %>% 
  filter(n() == 1) %>% 
  View()

# cocktails with 6 ingredients
cocktails %>% 
  group_by(name) %>% 
  filter(n() == 6) %>% 
  View()
```

```{r}
# how big is each cocktail?
cocktails %>% 
  count(measure, sort = TRUE)

# parse measurements first!
cocktails %>% 
  filter(str_detect(measure, "oz")) %>% 
  separate(measure, c("amount", "unit"), sep = " ") %>% 
  count(unit, sort = TRUE)

sizes <- cocktails %>% 
  filter(str_detect(measure, "oz"))  %>% 
  mutate(oz = str_replace(measure, " oz", "")) %>% 
  mutate(oz = str_replace(oz, " ?1/2", ".5")) %>% 
  mutate(oz = str_replace(oz, " ?1/4", ".25"))  %>% 
  mutate(oz = str_replace(oz, " ? ?3/4", ".75")) %>%
  mutate(oz = str_replace(oz, " ?1/3", ".33")) %>% 
  mutate(oz = str_replace(oz, " ?2/3", ".66")) %>% 
  mutate(oz = as.numeric(oz))

filter(sizes, oz > 3)
filter(sizes, oz > 10)


total_sizes <- sizes %>% 
  group_by(name) %>% 
  summarise(n = n(),
            oz = sum(oz))

total_sizes %>% 
  filter(oz < 20) %>% 
  ggplot(aes(oz)) + 
  geom_histogram(binwidth = 0.5)


total_sizes %>% 
  filter(oz > 6) %>% 
  semi_join(cocktails, ., by = "name")

cocktails %>% 
  filter(str_detect(ingredient, "bitters"))


sizes <- cocktails %>% 
  filter(str_detect(measure, "oz"))  %>% 
  filter(!str_detect(ingredient, fixed("bitters", ignore_case = TRUE))) %>% 
  mutate(oz = str_replace(measure, " oz", "")) %>% 
  mutate(oz = str_replace(oz, " ?1/2", ".5")) %>% 
  mutate(oz = str_replace(oz, " ?1/4", ".25"))  %>% 
  mutate(oz = str_replace(oz, " ? ?3/4", ".75")) %>%
  mutate(oz = str_replace(oz, " ?1/3", ".33")) %>% 
  mutate(oz = str_replace(oz, " ?2/3", ".66")) %>% 
  mutate(oz = as.numeric(oz))


sizes %>% 
  group_by(ingredient = tolower(ingredient)) %>% 
  summarise(n = n(),
            oz = mean(oz)) %>% 
  filter(n > 5) %>% 
  arrange(desc(oz)) %>% 
  head(20)

sizes %>% 
  group_by(ingredient) %>% 
  summarise(n = n(),
            oz = mean(oz)) %>% 
  filter(n > 5) %>% 
  arrange(desc(oz)) %>% 
  head(20)


non_spirit <- c("Chilled Champagne", "Water", "Orange Juice", "Cranberry Juice",
                "Light Cream (if desired)", "Fresh orange juice", "Orange juice")

sizes <- cocktails %>% 
  filter(str_detect(measure, "oz"))  %>% 
  filter(!str_detect(ingredient, fixed("bitters", ignore_case = TRUE))) %>% 
  filter(!ingredient %in% non_spirit) %>% 
  mutate(oz = str_replace(measure, " oz", "")) %>% 
  mutate(oz = str_replace(oz, " ?1/2", ".5")) %>% 
  mutate(oz = str_replace(oz, " ?1/4", ".25"))  %>% 
  mutate(oz = str_replace(oz, " ? ?3/4", ".75")) %>%
  mutate(oz = str_replace(oz, " ?1/3", ".33")) %>% 
  mutate(oz = str_replace(oz, " ?2/3", ".66")) %>% 
  mutate(oz = as.numeric(oz))
```



```{r}
# what are the primary ingredients?

cocktails %>% 
  count(ingredient = tolower(ingredient), sort = TRUE) %>% 
  head(20)

cocktail <- cocktails %>% 
  mutate(ingredient = tolower(ingredient))

standard_ingredients <- tribble(
  ~ingredient,          ~standard_name,
  "fresh lemon juice",  "lemon juice",
  "juice of a lemon",   "lemon juice",
  "fresh lime juice",   "lime juice",
  "juice of a lime",    "lime juice",
  
  )

ingredient_changes <- cocktail %>% 
  select(name, ingredient_number, ingredient) %>% 
  right_join(standard_ingredients) %>% 
  select(name, ingredient_number, ingredient = standard_name)

cocktail %>% 
  rows_update(ingredient_changes, by = c("name", "ingredient_number")) %>%
  count(ingredient, sort = TRUE) %>% 
  head(20)
  
```






